services:
  frontend:
    build:
      context: ./frontend
      target: ${APP_ENV}
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      BACKEND_URL: "/api"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: ${APP_ENV}
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - FLASK_ENV=${APP_ENV}
