services:
  frontend:
    build:
      context: ./frontend
      target: ${APP_ENV}
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${APP_ENV}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: ${APP_ENV}
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=${APP_ENV}
